const SETLOGINSTATUS = 'SETLOGINSTATUS'
const SETINFO = 'SETINFO'
const SETREGISTERID = 'SETREGISTERID'
const SETPERSONALID = 'SETPERSONALID'
export { SETLOGINSTATUS, SETINFO, SETREGISTERID, SETPERSONALID }
